<Project>
    <PropertyGroup>
        <ValheimGamePath>C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath>C:\Users\malco\AppData\Roaming\com.kesomannen.gale\valheim\profiles\Default\BepInEx</BepInExPath>
        <CorlibPath>$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
        <PublicizedAssembliesPath>$(ValheimGamePath)\valheim_Data\Managed\publicized_assemblies</PublicizedAssembliesPath>
        <CopyOutputDLLPath>C:\Users\malco\Documents\GitHub\TerrainHoe\Thunderstore</CopyOutputDLLPath>
        <CopyOutputDLLPath2>C:\Users\malco\AppData\Roaming\com.kesomannen.gale\valheim\profiles\test 1.0\BepInEx\plugins\JamesJonesTV-MoreTerrainTypes</CopyOutputDLLPath2>
        <AfterTargets>ILRepacker</AfterTargets> 
    </PropertyGroup>
</Project>